### ISSUE TITLE
Targeting own Postgres instead of creating a Postgres service

### ISSUE THREAD

**Issue by rbozan** [th0th/helm-charts#1]
Hi, I'd like to use this Helm chart but the problem is that the Postgres service seems to be mandatory. Most production environments have something more robust, like an operator, to handle Postgres. 

Can we somehow disable the creation of this Postgres service and target our own database instead?

Some related files are:
https://github.com/th0th/helm-charts/blob/42a7e28a10470a4d3f4af1330c5e49e49db8df84/charts/listmonk/templates/statefulset-postgres.yaml
https://github.com/th0th/helm-charts/blob/42a7e28a10470a4d3f4af1330c5e49e49db8df84/charts/listmonk/templates/service-postgres.yaml

**Comment by th0th** [comment]
Hey @rbozan, yeah sound like a good idea to make the postgres statefulset optional. I think adding an option to `values.yaml`, and making the whole resource in `statefulset-postgres.yaml` conditional would do the trick. If you send a PR, I would love to review 💐
