### ISSUE TITLE
the database does not appear to be setup. Run --install.

### ISSUE THREAD

**Issue by alebeta90** [th0th/helm-charts#4]
Hi,

When running the helm chart for listmonk it gives message

the database does not appear to be setup. Run --install.

Do I need to perform previous steps before launching the helm?

Bests

**Comment by th0th** [comment]
Hi @alebeta90, it should actually run the install itself when it is running for the first time. I released `v0.1.1` attempting to fix, can you please try it?

**Comment by alebeta90** [comment]
Hi @th0th let me try the new version and will let you know.

**Comment by alebeta90** [comment]
@th0th got the following message

```
❯ kubectl -n listmonk-prod logs --tail 200 -f listmonk-listmonk-6d5d694496-dxb9w
2024/10/03 13:08:47 main.go:102: v3.0.0 (f9120d9 2024-02-04T11:20:27Z, linux/amd64)
2024/10/03 13:08:47 init.go:150: reading config: config.toml
2024/10/03 13:08:47 init.go:289: connecting to db: listmonk-postgres:5432/listmonk

** first time (idempotent) installation **

continue (y/N)?  2024/10/03 13:08:47 install.go:36: error reading value from terminal: EOF
```

It is expecting interaction from terminal? passing "yes" ?

**Comment by alebeta90** [comment]
we have to pass "yes" in here? https://github.com/th0th/helm-charts/blob/main/charts/listmonk/templates/deployment-listmonk.yaml#L22

**Comment by th0th** [comment]
Yep, apparently :) I released `v0.1.2` with that fixed. Can you give another go?

**Comment by alebeta90** [comment]
ok updated version, but now it seems we have a DB setup. But still the service is crashing

```
❯ kubectl -n listmonk-prod get pods
NAME                                 READY   STATUS             RESTARTS      AGE
cloudflared-758fd64bb4-5s7dm         1/1     Running            0             117m
cloudflared-758fd64bb4-84q4v         1/1     Running            0             117m
listmonk-listmonk-6fb6d6bf47-hgqxz   0/1     CrashLoopBackOff   4 (79s ago)   2m46s
listmonk-postgres-0                  1/1     Running            0             117m
```

Logs
```
❯ kubectl -n listmonk-prod logs --tail 200 -f listmonk-listmonk-6fb6d6bf47-hgqxz
2024/10/03 13:52:20 main.go:102: v3.0.0 (f9120d9 2024-02-04T11:20:27Z, linux/amd64)
2024/10/03 13:52:20 init.go:150: reading config: config.toml
2024/10/03 13:52:20 init.go:289: connecting to db: listmonk-postgres:5432/listmonk

** first time (idempotent) installation **

2024/10/03 13:52:20 install.go:52: skipping install as database appears to be already setup
```
if database is already setup, it should not work? maybe in this case is something connected to listmonk itself?

**Comment by alebeta90** [comment]
@th0th I think it might be an issue from listmonk itself?

https://github.com/knadh/listmonk/blob/master/cmd/install.go#L53

if the database is setup, it seems they are killing exiting the process lol. And it can not continue with the starting of the program

**Comment by alebeta90** [comment]
Reading the recent issues they are mentioning the following

https://github.com/knadh/listmonk/issues/1887

one has to use a full command :

`./listmonk --yes --idempotent --install --upgrade && ./listmonk --static-dir={{ listmonk_static_dir }}"`

So it takes care of installing/upgrading and then it starts the process itself.


We could use that method, or add a initContainer to run the idempotent install and then the main container that just runs the app

**Comment by alebeta90** [comment]
@th0th I created the PR https://github.com/th0th/helm-charts/pull/5

Maybe it does help?

**Comment by th0th** [comment]
This time, instead of blindly publishing, I tried to install on my local cluster. So, hopefully it will really be resolved with this version 😅

**Comment by alebeta90** [comment]
Ok, all good now it is working properly thanks!

I saw there is a PR to use external db, will it be merged?

**Comment by th0th** [comment]
Good to hear :)

I will definitely have a look at those PRs when I have time.

**Comment by alebeta90** [comment]
Thanks man, if you need any help let me know. I will be improving my deployment so maybe I will be bothering you with some PR too if needed

**Comment by th0th** [comment]
Anytime! All questions, and contributions are welcome :)
